baseurl: ""
title: JellorBlog
email: guodong9211@gmail.com
name: JellorBlog
description: "To be a coder."
url: "http://jellor.github.io"
markdown: kramdown

# custem post URL format, pretty => /:categories/:year/:month/:day/:title/
permalink: pretty

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

timezone: Asia/Shanghai
encoding: utf-8
