baseurl: ""
title: Jellor
email: guodong9211@gmail.com
name: Jellor
description: "jellor blog"
url: "http://jellor.github.io"
markdown: kramdown
permalink: pretty

plugins:
 - jekyll-feed
 - jekyll-seo-tag

timezone: Asia/Shanghai
encoding: utf-8
